# Generated by Django 5.1.3 on 2024-12-07 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_contactformlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
                ('title', models.CharField(max_length=255)),
                ('authur', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
            ],
        ),
    ]
