# Generated by Django 5.1.3 on 2024-12-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
