# Generated by Django 5.1.3 on 2024-12-07 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_blog_authur'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App.authur'),
        ),
    ]
